### ISSUE TITLE
AsmodeusCore and FogWorld issue

### ISSUE THREAD

**Issue by AechtRob** [Hennamann/Fog-World#10]
The latest update of AsmodeusCore mod (AsmodeusCore-1.12.2-0.0.13.jar) has interfered and messed up the fog in the FogWorld mod (https://www.curseforge.com/minecraft/mc-mods/fog-world - FogWorld-1.12-1.1.0-b15-universal.jar). It sort of inverts, so the closer you get to something the foggier it is. If you're on the ground you can't see anything except things very far away :/  (Forge 14.23.5.2847)

**Comment by Hennamann** [comment]
Getting back to you on this a bit late, i no longer intend to support the 1.12 version of this mod.
Issues with other mods messing with Fog rendering is a hard problem to fix unfortunatley so issues like this will happen regardless of what i do code wise…

Closing this issue since 1.12 is unsupported.
