### ISSUE TITLE
[QUESTION] Fog-World and Client-Server Compatibility?

### ISSUE THREAD

**Issue by DragonRaiderII** [Hennamann/Fog-World#5]
To begin, I just wanted to state that this mod has some potential.  I've always wanted to have better control over the in-game fog.

That said, I was wondering if installing this on my game's client would restrict me from joining a modded server that doesn't also have the mod installed.

**My question is actually two-fold:**

- If I add this mod to my game, does any multiplayer server I join also need to install the mod?
- If the server has the mod installed, will any connecting clients also need to install to be able to join?

I appreciate any information regarding the topic, as I have recently began to learn coding for non-java applications, and I personally enjoy learning about how client-server systems tend to behave and interact with each other.

Cheers,
_-- DragonRaiderII_

**Comment by Hennamann** [comment]
Sorry about replying so late, i've been on a bit of a hiatus from MC modding. If the mod is installed server side, Forge will require all clients to have it installed, if it's only installed locally forge won't care. And since the mod only affects rendering the mod will work exactly as intended on servers. (Unless something has changed with the client-server relationship in MC)
